import { defineConfig } from 'vite';
import { cpSync, existsSync, readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));

// Rewrite dist/sw.js's precache manifest to exactly what the build emitted
// (hashed CSS/fonts/icons + the copied classic scripts) and stamp a
// content-derived build id, so the service worker precaches real files instead
// of the raw source paths (which don't exist after bundling) and its cache
// busts automatically when output changes. Runs after copyLegacyRuntime has
// placed sw.js into dist.
function generateServiceWorker(out) {
  const swPath = resolve(out, 'sw.js');
  if (!existsSync(swPath)) return;
  const files = [];
  const walk = (dir, rel = '') => {
    for (const name of readdirSync(dir)) {
      const abs = resolve(dir, name);
      const r = rel ? `${rel}/${name}` : name;
      if (statSync(abs).isDirectory()) walk(abs, r);
      else if (r !== 'sw.js') files.push('./' + r.replace(/\\/g, '/'));
    }
  };
  walk(out);
  files.sort();
  const cssFile = files.find((f) => /\/assets\/index-.*\.css$/.test(f)) || '';
  const buildId = 'build-' + ((cssFile.match(/index-([^./]+)\.css$/) || [, 'dev'])[1]);
  const header =
    '// Precache manifest + build id auto-generated by vite.config.js — do not edit.\n' +
    `self.__BUILD_ID__ = ${JSON.stringify(buildId)};\n` +
    `self.__PRECACHE__ = ${JSON.stringify(files)};\n\n`;
  writeFileSync(swPath, header + readFileSync(swPath, 'utf8'));
}

// Phase-0 baseline: the app's JavaScript is still classic, global-scope
// `<script>` files (storage.js + js/*.js) plus two vendored non-module
// libraries. Vite/Rollup can only bundle ES modules, so it cannot fingerprint
// these yet — it hashes the CSS and static assets and leaves the <script src>
// tags pointing at their original relative paths. This plugin copies those
// still-classic files into dist verbatim so the built app runs identically.
// As the scripts are converted to ES modules in later steps, they drop out of
// this list and Vite fingerprints them instead.
function copyLegacyRuntime() {
  return {
    name: 'copy-legacy-runtime',
    apply: 'build',
    closeBundle() {
      const out = resolve(root, 'dist');
      // [from, to] relative to repo root / dist respectively.
      const items = [
        ['storage.js', 'storage.js'],
        ['js', 'js'],
        ['vendor/toastui/toastui-editor-all.min.js', 'vendor/toastui/toastui-editor-all.min.js'],
        ['vendor/morphdom/morphdom-umd.min.js', 'vendor/morphdom/morphdom-umd.min.js'],
        ['sw.js', 'sw.js'],
        // Vite emits the hashed webmanifest under assets/ but keeps its icon
        // src paths relative ("icons/..."), so they resolve to assets/icons/*.
        ['icons', 'assets/icons'],
      ];
      for (const [from, to] of items) {
        const src = resolve(root, from);
        if (existsSync(src)) cpSync(src, resolve(out, to), { recursive: true });
      }
      // sw.js is now in dist; rewrite its precache manifest from the real output.
      generateServiceWorker(out);
    },
  };
}

export default defineConfig({
  // Relative base so the build works under a GitHub Pages project subpath,
  // matching how the current (non-built) app loads everything relatively.
  base: './',
  plugins: [copyLegacyRuntime()],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
});
