import './state-calculations.test.mjs';
import './storage-migrations.test.mjs';
import './search-index.test.mjs';
import './service-worker.test.mjs';
import './dashboard-performance.test.mjs';
import './maintainability-characterization.test.mjs';
import './markup-helpers.test.mjs';
import './interaction-contract.test.mjs';
import './runtime-performance.test.mjs';
