/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=C:\Users\nguye\Desktop\docvault-qa-document-hub\wrangler.identity-burst.jsonc --include-runtime=false C:\Users\nguye\Desktop\docvault-qa-document-hub\workers\identity-burst-configuration.d.ts` (hash: f30c61b52a05fde672c5f54fccf199a9)
interface __BaseEnv_Env {
	AUTH_BURST_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./identity-burst-limiter");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
